[package]
name = "afl-clang-fast-rust"
version = "0.1.0"
edition = "2021"

[features]
default = []
USE_TRACE_PC = []
MESSAGES_TO_STDOUT = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
